### ISSUE TITLE
EmailToTeam failed by 2-minute time limit

### ISSUE THREAD

**Issue by aslanovsergey** [demianrasko/Dynamics-365-Workflow-Tools#103]
### Expected behavior and actual behavior.
Several times I saw EmailToTeam work longer then 2 minutes which caused a workflow to fail by threshold.

`Message:  Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.Class.EmailToTeam: System.TimeoutException: Couldn’t complete execution of the custom activity msdyncrmWorkflowTools.Class.EmailToTeam plug-in within the 2-minute time limit. 
`

```
Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.Class.EmailToTeam]
[msdyncrmWorkflowTools (1.0.51.1): Email To Team]

Load CRM Service from context --- OK



Error Message:

Unhandled Exception: Microsoft.Crm.CrmException: Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.Class.EmailToTeam: System.TimeoutException: Couldn’t complete execution of the custom activity msdyncrmWorkflowTools.Class.EmailToTeam plug-in within the 2-minute time limit.
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass24_0.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePluginContainer.Execute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
```

### CRM Version - online/onpremise - WorkflowTools version
D365 9.0 / 1.51.1

**Comment by donalmc** [comment]
I experienced something similar with Update Child Records and came one here to see if anyone else had.
It seems that, unless you are On Prem, there is nothing that can be done about the 2 minute limit with custom activities.
For me, this topped out at around 1400 records
See [here](https://community.dynamics.com/crm/b/mohamedmostafacrmblog/archive/2014/10/29/overcoming-the-2-minutes-limit-on-execution-of-microsoft-dynamics-crm-online-workflow-activities-and-plugins-msdyncrm) for more info,

**Comment by demianrasko** [comment]
There is an execution limit in CRM of 2 minutes, in onpremise you can increase that parameter.
you must check that there is not to many users in the team, that could cause the 2 minute issue.
