### ISSUE TITLE
1.0.53.0 - Set Process Stage - Unhandled exception

### ISSUE THREAD

**Issue by Dan-Newton** [demianrasko/Dynamics-365-Workflow-Tools#112]
### Expected behavior and actual behavior.
I have a simple condition based action using "Set Process Stage" basically if field x is yes move from process stage a to b.

When running the workflow it fails with the below error:

`Sync workflow failed with error message - Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute):  msdyncrmWorkflowTools.Class.SetProcessStage: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass24_0.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePluginContainer.Execute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --

Exception type: Microsoft.Crm.Workflow.Services.InvalidCustomActivityExecutionException
Message: An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute):  msdyncrmWorkflowTools.Class.SetProcessStage: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Activities.WorkflowApplication.Invoke(Activity activity, IDictionary`2 inputs, WorkflowInstanceExtensionManager extensions, TimeSpan timeout)
   at System.Activities.WorkflowInvoker.Invoke(Activity workflow, IDictionary`2 inputs, TimeSpan timeout, WorkflowInstanceExtensionManager extensions)
   at Microsoft.Crm.Workflow.SynchronousRuntime.SynchronousWorkflowActivityHost.ExecuteWorkflowUsingInvoker(Activity workflow, ICommonWorkflowContext context)
   at Microsoft.Crm.Workflow.SynchronousRuntime.SynchronousWorkflowActivityHost.StartWorkflow(WorkflowActivationData activationData, ICommonWorkflowContext context)
-- End stack trace --

, error code - -2147220891`

### Steps to reproduce the problem (screenshots are really usefull)

![image](https://user-images.githubusercontent.com/35452530/50104130-3487c480-0221-11e9-9fa1-01b66095ff0c.png)

![image](https://user-images.githubusercontent.com/35452530/50104161-479a9480-0221-11e9-8bb8-94832c7716a4.png)

### CRM Version - online/onpremise - WorkflowTools version

WorkflowTools - 1.0.53.0
CRM - Version 1710 (9.1.0.996) online

**Comment by demianrasko** [comment]
Hi, please share with me the parameters you are using and a screenshot of the process and I will try to reproduce your exact scenario.

Thanks

**Comment by Dan-Newton** [comment]
Hi @demianrasko 

Process:
![image](https://user-images.githubusercontent.com/35452530/50176024-3a030e80-02f6-11e9-98c1-261343bf125a.png)

Workflow:
![image](https://user-images.githubusercontent.com/35452530/50176182-a251f000-02f6-11e9-9331-3634daea332a.png)

![image](https://user-images.githubusercontent.com/35452530/50176142-877f7b80-02f6-11e9-9109-ba742bf35833.png)

So basically if field A under "Propose" is yes then move to "Contract & Close" is what I'd like to do but receive the above error message.

Any help would be appreciated

**Comment by demianrasko** [comment]
Hi Dan, I just testing the same behaviour en my environment and is should work.
Here I share with you some screenshots of my tests. Could you share with me the solution and I try too import it in same way you have it? maybe you have any other workflow or plugins?

![set process stage](https://user-images.githubusercontent.com/18124945/50382165-9b7e0100-0699-11e9-9d79-3806a0e6bcb9.gif)
![set process stage2](https://user-images.githubusercontent.com/18124945/50382166-9b7e0100-0699-11e9-8ffd-70a75a76b9a5.gif)
![set process stage3](https://user-images.githubusercontent.com/18124945/50382167-9b7e0100-0699-11e9-9962-e7f17a95c7f9.gif)
![set process stage4](https://user-images.githubusercontent.com/18124945/50382168-9b7e0100-0699-11e9-879a-d4032ce0b634.gif)
![set process stage5](https://user-images.githubusercontent.com/18124945/50382169-9c169780-0699-11e9-9388-82953a5dec33.gif)
