### ISSUE TITLE
Roll Up Issue

### ISSUE THREAD

**Issue by richardlondon** [demianrasko/Dynamics-365-Workflow-Tools#113]
### Expected behavior and actual behavior.
Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.RollupFunctions]

[msdyncrmWorkflowTools (1.0.53.0): Rollup Functions]

Load CRM Service from context --- OK

_FetchXML=<fetch output-format="xml-platform" distinct="false" version="1.0" mapping="logical"> <entity name="contact"><attribute name="emailaddress1"/> <filter type="and"> <condition attribute="emailaddress1" operator="eq" value="s.xxxxxxx@8build.co.uk"/> </filter> </entity> </fetch>

Value: xxxxxxx@8build.co.uk

Value: s.xxxxxxx@8build.co.uk

Value: s.xxxxxxxx@8build.co.uk

Query Data --- Done

Error Message:

Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute):  msdyncrmWorkflowTools.RollupFunctions: System.FormatException: Input string was not in a correct format.

   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)

   at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass24_0.<Execute>b__0()

   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)

   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)

   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)

   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePluginContainer.Execute(IServiceProvider serviceProvider)

   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)

-- End stack trace --

### Steps to reproduce the problem (screenshots are really usefull)
<fetch distinct="false" version="1.0" output-format="xml-platform" mapping="logical">
<entity name="contact">
<attribute name="fullname"/>
<attribute name="emailaddress1"/>
<filter type="and">
<condition attribute="emailaddress1" operator="eq" value="s.xxxxxx@8build.co.uk"/>
</filter>
</entity>
</fetch>
### CRM Version - online/onpremise - WorkflowTools version
Online V9. Latest  Dynamics365WorkflowTools_1_0_52_1_8.2_managed.zip

**Comment by richardlondon** [comment]
Hi,
The query seems to fail if there is an @ symbol in the fetch string. If I take this out it seems to work OK.
However, I cannot check for the existence of an email address in the contact record without it. Unless you know of an alternative way?

**Comment by demianrasko** [comment]
Hi Richard, I just tested with this FetchXML and it works fine:
<fetch distinct="false" version="1.0" output-format="xml-platform" mapping="logical">
<entity name="contact">
<attribute name="fullname"/>
<attribute name="emailaddress1"/>
<filter type="and">
<condition attribute="emailaddress1" operator="eq" value="s.sharma@8build.co.uk"/>
</filter>
</entity>
</fetch>

I think in the first error, your FetchXML input parameter whas just this:
Value: xxxxxxx@8build.co.uk
Value: s.xxxxxxx@8build.co.uk
Value: s.xxxxxxxx@8build.co.uk

(this is not a correct FetchXML query format).

please check it again that it works fine.

thanks!

**Comment by richardlondon** [comment]
Hi Damian,


Thank you for your email. Did you see the attached Fetch XML file?


I have used this function before and it works fine. I just cannot get this Fetch XML to work. Works ok without the @ symbol in the email string. Strange. Thanks for your help with this. 


Merry Christmas to you.


Richard 




Get Outlook for Android







On Sun, Dec 23, 2018 at 9:09 AM +0000, "Demian Adolfo Raschkovan" <notifications@github.com> wrote:












Closed #113.
