### ISSUE TITLE
Error : Required field 'FieldName' is missing

### ISSUE THREAD

**Issue by rupakraj6** [demianrasko/Dynamics-365-Workflow-Tools#138]
### Expected behavior : Roll up should be calculated
        Real behavior : BPF throws error on UI 

### Steps to reproduce the problem (screenshots are really usefull)
![image](https://user-images.githubusercontent.com/16092877/58016243-ba82a100-7b1a-11e9-8f4e-bf664ff6fc30.png)

stacktrace :- 

Sync workflow failed with error message - Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: Required field 'FieldName' is missing
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass24_0.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePluginContainer.Execute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --

    

### CRM Version - online/onpremise - WorkflowTools version
        online version 9.1

**Comment by demianrasko** [comment]
Hi rupakraj6 , what action are you using? can you share screenshots of all the configuration?
thanks!

**Comment by ChandraTerli** [comment]
I am getting the same error, can sombody help? I am trying to trigger Rollup using "msdyncrmWorkflowTools (1.0.57.0):Calculate Rollup Field" and get this error.

**Comment by ChandraTerli** [comment]
Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.CalculateRollupField]
[msdyncrmWorkflowTools (1.0.57.0): Calculate Rollup Field]
Load CRM Service from context --- OK
ParentObjectTypeCode=10452--ParentId=0511afc9-16f2-ea11-a815-000d3a1026fe


Error Message:

Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: Required field 'FieldName' is missing
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass26_0.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.CDSExecute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --

**Comment by ChandraTerli** [comment]
Neermind, I got it worked.
The FieldName parameter should be set to the name of the rollup field (e.g. new_myrollupfield). I was referencing it using the object instead of manual specifying manual field name.
