### ISSUE TITLE
Force Calculate Rollup Field not working

### ISSUE THREAD

**Issue by MarcLongtin** [demianrasko/Dynamics-365-Workflow-Tools#151]
I'm running into an issue with the Dynamics-365-Workflow-Tools, especially with the Force Calculate Rollup Field. I am trying to use it in a workflow and I'm getting the following error : 
Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: 'Account' entity doesn't contain attribute with Name = '1' and NameMapping = 'Platform'. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=7201709, MinActiveRowVersion=7201709
at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass24_0.<Execute>b__0()
at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)
at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePluginContainer.Execute(IServiceProvider serviceProvider)
at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --
I need help figuring out what the issue is. I have correctly indicated the rollup field and the parent entity URL in the function required fields. 

This is happens when the WF (first step) call to force the calculation of the Rollup field.

**Comment by demianrasko** [comment]
Hi MarcLongtin , 
I think I will need more details in order to address this issue. please share with me screenshots, the field name, etc...

**Comment by arcish** [comment]
I am experiencing same issue. did anyone find solution ?

**Comment by CaalarYlmaz** [comment]
I am experiencing same issue !!

**Comment by CaalarYlmaz** [comment]
I think there is a small mistake in the workflow because in my case it's looking field with name '€78,500.00'. This is my field's value not the field's name. 

Plugin Trace:
Error Message:
Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: **'osds_clientassessment' entity doesn't contain attribute with Name = '€78,500.00'** and NameMapping = 'Platform'. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=6083433, MinActiveRowVersion=6083433
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass24_0.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.CDSExecute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --

**Comment by arcish** [comment]
It was resolved for me I was adding fields reference instead of field name, Check the attached screenshot.
![1](https://user-images.githubusercontent.com/7419411/69970074-94878180-14eb-11ea-96d9-7e1204cd86f0.png)

**Comment by CaalarYlmaz** [comment]
arcish 

> It was resolved for me I was adding fields reference instead of field name, Check the attached screenshot.
> ![1](https://user-images.githubusercontent.com/7419411/69970074-94878180-14eb-11ea-96d9-7e1204cd86f0.png)

Thanks very much for your help. I was adding field reference when I wrote directly field name it solved for me too. Thanks a lot.
