### ISSUE TITLE
Exception : Multiple interfaces with the name 'Workflow Essentials' exist. 

### ISSUE THREAD

**Issue by SA-CRM** [demianrasko/Dynamics-365-Workflow-Tools#165]
I am running a workflow that parses date entered on an entity instance and gets the year part and use it to update another number field and text field with the year value 
**Example Steps** 
date value : 27/10/2019 
1-  Get the year part using : Gap Date Functions (6.1.0.3):Gap.Dates.ParseDate  
2-  update the number field of the year  using the value retrieved 
3-  remove commas from the number format year (2,019) using Gap String Functions (6.1.0.3):Gap.StringFunctions.StringReplace

This used to work of single record add / update  from the interface however in importing multiple records using excel sheet it caused the following exception

Unhandled exception: 
Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]
Message: System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> Microsoft.Crm.CrmException: An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute):  Gap.Dates.ParseDate: System.InvalidOperationException: Multiple interfaces with the name 'Workflow Essentials' exist.  

I changed the workflow to run only on demand and removed the running conditions after create / update and allowed only on demand and run it again on 1 record and the same exception appeared again even though it's one record and only 1 user running it

**the details from the system job :** 
Plugin Trace:

[Gap Date Functions: Gap.Dates.ParseDate]
[Gap Date Functions (6.1.0.3): Gap.Dates.ParseDate]

Error Message:

Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute):  Gap.Dates.ParseDate: System.InvalidOperationException: Multiple interfaces with the name 'Workflow Essentials' exist.
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass24_0.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePluginContainer.Execute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --

**Comment by demianrasko** [comment]
Hi SA-CRM, 
I think this is not related this project, maybe is regarding another CRm tool.

thanks!
