### ISSUE TITLE
.msg attachment is not supporting

### ISSUE THREAD

**Issue by chinmay367** [demianrasko/Dynamics-365-Workflow-Tools#167]
### Expected behavior and actual behavior.
In CRM , we have attachment section in our solution where users can upload different format files.
In one workflow emails are send to associated users with the attachment. But this custom tool is not supporting .msg attachments(other extensions are working fine) and gives business process error.

### Steps to reproduce the problem (screenshots are really usefull)
![1](https://user-images.githubusercontent.com/24872735/68184954-684d1380-ffc6-11e9-936e-d433fd2ca258.PNG)

1. First step is CRM create email .
![2](https://user-images.githubusercontent.com/24872735/68184988-7733c600-ffc6-11e9-8ee4-f1c1fe837a82.PNG)

2. Second step is attaching the attachments( By dynamic URL)
![3](https://user-images.githubusercontent.com/24872735/68185006-7c911080-ffc6-11e9-95a6-fa31c06bcb58.PNG)

3. Third step is sending the email.
![4](https://user-images.githubusercontent.com/24872735/68185013-80249780-ffc6-11e9-8913-12e177465f09.PNG)

If there is attachment of .msg format, the workflow fails.

Stack trace of failure:-
Sync workflow failed with error message - Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: An unexpected error occurred.
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass24_0.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePluginContainer.Execute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --

Exception type: Microsoft.Crm.Workflow.Services.InvalidCustomActivityExecutionException
Message: An unexpected error occurred.
   at System.Activities.WorkflowApplication.Invoke(Activity activity, IDictionary`2 inputs, WorkflowInstanceExtensionManager extensions, TimeSpan timeout)
   at System.Activities.WorkflowInvoker.Invoke(Activity workflow, IDictionary`2 inputs, TimeSpan timeout, WorkflowInstanceExtensionManager extensions)
   at Microsoft.Crm.Workflow.SynchronousRuntime.SynchronousWorkflowActivityHost.ExecuteWorkflowUsingInvoker(Activity workflow, ICommonWorkflowContext context)
   at Microsoft.Crm.Workflow.SynchronousRuntime.SynchronousWorkflowActivityHost.StartWorkflow(WorkflowActivationData activationData, ICommonWorkflowContext context)
-- End stack trace --

, error code - -2147220891

### CRM Version - online/onpremise - WorkflowTools version
msdyncrmWorkflowTools (1.0.54.2)

**Comment by demianrasko** [comment]
Hi chinmay367,
please try with the parameter "Retrieve ActivityMimeAttachment" to false. if you set to true, it only works for email and appointments.

thanks!
