### ISSUE TITLE
Issue with Calculate Rollup Field - The specified field does not exist in Microsoft Dynamics 365.

### ISSUE THREAD

**Issue by arcish** [demianrasko/Dynamics-365-Workflow-Tools#169]
I am getting error while using Calculate Rollup fields WFA, My dynamics 365 version is (9.1.0.9627) online. When I execute Workflow I am getting following error \ 'target' entity doesn't contain attribute with Name = '12' and NameMapping = 'Platform'. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=512869723, MinActiveRowVersion=512869723    Suggest what I'm doing wrong/
![Capture](https://user-images.githubusercontent.com/7419411/68500633-2fad7400-022a-11ea-8ebc-3b9cf55f4aa2.PNG)

**Comment by CaalarYlmaz** [comment]
I am experiencing same issue !!

**Comment by CaalarYlmaz** [comment]
I think there is a small mistake in the workflow because in my case it's looking field with name '€78,500.00'. This is my field's value not the field's name. 

Plugin Trace:
Error Message:
Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: **'osds_clientassessment' entity doesn't contain attribute with Name = '€78,500.00'** and NameMapping = 'Platform'. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=6083433, MinActiveRowVersion=6083433
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass24_0.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.CDSExecute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --

**Comment by rsilver875** [comment]
This is happening to me as well. I am running on 2019, release wave 2 (9.1.0000.10743) and I'm using 1.0.57.0_for.CDS. Have there been any fixes or is this still happening to others?

**Comment by arcish** [comment]
Hello Guys, This issue is resolved for me. I was passing the field reference of rollup field instead or name, 
As per the error description, it is showing the **value** of the rollup filed, because you are passing field reference in the workflow parameter. If you pass hardcoded field name it will resolve the issue.

**Comment by ishantg28** [comment]
Hi i am getting the same Problem can You please tell how to resolve this error
