### ISSUE TITLE
Type is not resolved for member 'Newtonsoft.Json.JsonReaderException,msdyncrmWorkflowTools

### ISSUE THREAD

**Issue by CryogenicPotato** [demianrasko/Dynamics-365-Workflow-Tools#185]
Hello,

I am facing an issue that for some reason only occurs on the production Dynamics 365 server.
I have a Custom Action that makes use of the **msdyncrmWorkflowTools.ParseJSON** function, in the development environment it just works fine, but in production the same custom action throws the following error:

```
System.Runtime.Serialization.SerializationException: Type is not resolved for member 'Newtonsoft.Json.JsonReaderException,msdyncrmWorkflowTools, Version=1.0.52.1, Culture=neutral, PublicKeyToken=416e876b9bee261e'.
   at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.Execute(IOrganizationServiceFactory organizationServiceFactory, String customActivityTypeName, IExecutionContext requestContext, Dictionary`2 sandboxServices, Boolean useDrawbridgeEnabled, Boolean chaosFailAppDomain)
   at Microsoft.Crm.Sandbox.SandboxWorker.ExecuteCustomWorkflowActivity(SandboxCallInfo callInfo, SandboxCustomActivityExecutionContext requestContext, Guid pluginAssemblyId, Int32 sourceHash, String assemblyName, Guid pluginTypeId, String pluginTypeName, SandboxRequestCounter& workerCounter, Boolean returnTraceInfo): Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #CD758063
StackTrace:    at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, CorrelationToken correlationToken, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext)
   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Execute(OrganizationRequest request, ExecutionContext executionContext)
   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.ExecuteOperation(CrmODataExecutionContext context, EdmOperation edmOperation, Dictionary`2 parameters, Dictionary`2 boundParameters)
   at Microsoft.Crm.Extensibility.OData.ActionController.ProcessOperationRequest(String operationName, Dictionary`2 operationParameters, EntityReference entityReference, String boundEntityName, String boundEntityType)
   at Microsoft.Crm.Extensibility.OData.ActionController.<>c__DisplayClass11_0.<PostBoundAction>b__0()
```

I am using msdyncrmWorkflowTools version 1.0.52.1 on both development and production server, I'm stuck with this version because later managed solution versions import fail because it our Dynamics 365 9.0.11 On-Premise version is not supported.

Any ideas what could be causing this? Is there any prerequisite to fulfill to use Parse JSON method? Like having to manually register Newtonsoft.Json dll manually in the server GAC or something?

**Comment by demianrasko** [comment]
This was an issue, already solved in this version: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/releases/tag/1.0.58.0
