### ISSUE TITLE
Initiating User Errors

### ISSUE THREAD

**Issue by jjones419** [demianrasko/Dynamics-365-Workflow-Tools#192]
When using the Get Record ID and Rollup Functions pieces of Dynamics 365 Workflow Tools I am getting errors about parsing the guid for the InitiatingUserId value.  Below is one of the errors received.

 Sync workflow 'Lead Mgmt - Create task to follow up with the contact ' terminated with error 'System.Exception: Exception while parsing guid for InitiatingUserId value
	   at Microsoft.CDSRuntime.SandboxGrpcContracts.GrpcSandboxExecutionContext.ConvertToGuid(String stringGuid, String propertyName)
	   at Microsoft.CDSRuntime.SandboxGrpcContracts.GrpcSandboxCustomActivityExecutionContext..ctor(SandboxCustomActivityExecutionContext grpcContext)
	   at Microsoft.Xrm.RemotePlugin.Grpc.SandboxFabricCodeUnit.ExecuteCustomActivity(IExecutionContext context, Guid executionId, ISandboxFabricDuplexCommunicationHandler communicationHandler, String&amp; traceInfo)
	   at Microsoft.Xrm.RemotePlugin.Grpc.SandboxFabricCodeUnit.Execute(ILifetimeScope scope, IExecutionContext context, Guid executionId, String&amp; traceInfo)
	   at Castle.Proxies.Invocations.ISandboxFabricCodeUnit_Execute.InvokeMethodOnTarget()
	   at Castle.DynamicProxy.AbstractInvocation.Proceed()
	   at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricPluginTraceInterceptor.Intercept(IInvocation invocation, IExecutionContext context, Guid executionId)
	   at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricCodeUnitExecuteBaseInterceptor.Intercept(IInvocation invocation)
	   at Castle.DynamicProxy.AbstractInvocation.Proceed()
	   at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricClientTelemetryInterceptor.&lt;&gt;c__DisplayClass2_0.&lt;Intercept&gt;b__0(): Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #163AEE31'

**Comment by jjones419** [comment]
Any help with this would be greatly appreciated.  It only appears to happen in our dev environment which is on 17 while all of our other environments are on 16.  We have a project that is nearing its deadline so I am kind of in a crunch on this.  I plan to use the code as in QA but I wonder if these will start breaking when Microsoft pushes 17 to the rest of our instances.

**Comment by jjones419** [comment]
I have also opened a Microsoft support issue for this as I believe this has started breaking in our dev environment within the last week and we were pushed an automatic update over last weekend.  Prior to that we were not getting this issue.

**Comment by jjones419** [comment]
Just wanted to update this thread we were updated to CRM Online 9.1.0.18015 last night and this issue is still occurring.

**Comment by jjones419** [comment]
This ended up being a Microsoft bug in non production (sandbox) environments. They have released a fix.
