### ISSUE TITLE
SetProcessStage error V58

### ISSUE THREAD

**Issue by Couchiman** [demianrasko/Dynamics-365-Workflow-Tools#193]
**Expected Behaviour: Go back to previous Stage**

**Actual Behaviour is throwing this error:**

Active Stage ID ‘d5a5823e-9d40-dbc1-c447-53919c44b5ce’ does not match last Stage ID in Traversed Path 
‘821073c1-ee54-e150-5e8d-a4996bb4236c’. Please contact your system administrator.

**Plugin Trace:**

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.Class.SetProcessStage]
[msdyncrmWorkflowTools (1.0.58.0): Set Process Stage]
Load CRM Service from context --- OK
ObjectTypeCode=112--ParentId=6f1c2e78-7a53-4ea4-b0b9-7989aa4c1abf
[Dynamics.ChangeBPFandPhase.Execute] Process stage: Resolución
[Dynamics.ChangeBPFandPhase.Execute] Fetching the requested Stage.
Starting the update
Starting the update2

Error Message:

Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: Active Stage ID ‘d5a5823e-9d40-dbc1-c447-53919c44b5ce’ does not match last Stage ID in Traversed Path ‘821073c1-ee54-e150-5e8d-a4996bb4236c’. Please contact your system administrator.
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.<>c__DisplayClass24_0.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.CDSExecute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --

**Steps to Reproduce it**

1 - Create a BPF and advance it to Last Stage for Case entity
2 - Trigger Worklow to set the previous based on a condition field of the BPF
   --> The workflow should be configured with Record URL of a Case, BPF Refence, Previous process stage name

**CRM Dynamics V9.1 Online
Workflow Version 58**

**Comment by demianrasko** [comment]
Hi @Couchiman, Maybe you have an issue with the Stage Names, try to use it on CRM base language.
I just tested and it worked fine for me on online environment. I share the screenshots just in case they help you:
![error1](https://user-images.githubusercontent.com/18124945/87252138-1328a200-c471-11ea-8043-aef21d22a224.png)
![error2](https://user-images.githubusercontent.com/18124945/87252139-13c13880-c471-11ea-89b0-a0ea89124261.png)
![error3](https://user-images.githubusercontent.com/18124945/87252137-1328a200-c471-11ea-838f-6ac47df79b29.png)
![error4](https://user-images.githubusercontent.com/18124945/87252135-12900b80-c471-11ea-92f5-f52b66afee3c.png)
![error5](https://user-images.githubusercontent.com/18124945/87252136-12900b80-c471-11ea-94c6-671d095ca81a.png)
![error6](https://user-images.githubusercontent.com/18124945/87252134-11f77500-c471-11ea-8257-a8d4c9c31843.png)
![error7](https://user-images.githubusercontent.com/18124945/87252133-115ede80-c471-11ea-8681-6ec74fe3f362.png)

**Comment by Couchiman** [comment]
Ok. I will try that next time. Found that the traverse path was not "cleaning" the last step, that's the reason of the error. 
So i removed the component to make the change in a native way, directly updating the entity and start working
