### ISSUE TITLE
clone children not working on quote

### ISSUE THREAD

**Issue by yaghoubi** [demianrasko/Dynamics-365-Workflow-Tools#208]
hi,
when i used clone children on quote it not create clone quote's product, is clone children not support quote ?

**Comment by LisaDor** [comment]
We found out that it is possible for Quotes in "Draft" mode but not "Active" Quotes

**Comment by demianrasko** [comment]
Hi all, it should work, please share me all the details of your sample and if you have any error message.
Please share screenshots too and I'll try to help.

thansk!

**Comment by AbhisekBhansali** [comment]
Hi @demianrasko 

On Quote child record Quote product try to clone then throw an error.

Message: The detail cannot be updated because the parent is not editable.Detail:

![image](https://user-images.githubusercontent.com/68702676/105540237-e4db2780-5d1b-11eb-83b8-2129efb832b2.png)


Thanks

**Comment by AbhisekBhansali** [comment]
Hi All,

I got the issue, In CloneRecord need to pass targeted record

public Guid CloneRecord(string entityName, string objectId, string fieldstoIgnore, string prefix, string destinationId)
and add destinationId
newEntity.Attributes.Add(ChildentityName, new EntityReference("quote", new Guid(destinationId)));

![image](https://user-images.githubusercontent.com/68702676/105629975-2aa70580-5e6c-11eb-93a9-d76e41ab136a.png)

Thanks,

**Comment by JTMartin64** [comment]
Hello All,

I'm trying to use the msdyncrmWorkflowTools.CloneChildren workflow activity to copy the quote products to a quote I'm copying.  The first step of the workflow "copies the quote" successfully using the msdyncrmWorkflowTools.CloneRecord workflow activity.  I then try to create the child "quote products using the msdyncrmWorkflowTools.CloneChildren workflow activity.  The image below shows the setting for the workflow. 

![image](https://user-images.githubusercontent.com/34925015/111343709-12748b00-8652-11eb-8f2b-0b04f3a1e81c.png)

The message I get when if fails is below.  Do I have one of the values on properties of the call wrong or is this something that the tool wasn't designed to do (i.e. copy a quote and the related quote products).  Thank you in advance.  Jon 

Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.CloneChildren]
[msdyncrmWorkflowTools (1.0.61.1): msdyncrmWorkflowTools.CloneChildren]

Load CRM Service from context --- OK
ObjectTypeCode=1084--ParentId=9122c234-c664-eb11-a812-002248085164

Error Message:

Unhandled exception: 
Exception type: Microsoft.Crm.CrmException
Message: An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute):  msdyncrmWorkflowTools.CloneChildren: System.Exception: Index was outside the bounds of the array.
   at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricClientTelemetryInterceptor.<>c__DisplayClass3_0.<Intercept>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricClientTelemetryInterceptor.Intercept(IInvocation invocation, IExecutionContext context, SandboxFabricCallTracker sandboxFabricCallTracker)
   at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricCodeUnitExecuteBaseInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ISandboxFabricCodeUnitProxy.Execute(ILifetimeScope scope, IExecutionContext context, SandboxFabricCallTracker& sandboxFabricCallTracker)
   at Microsoft.Xrm.RemotePlugin.Client.SandboxFabricPlugin.<>c__DisplayClass5_1.<Execute>b__3()
   at Polly.Policy.<>c__DisplayClass150_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass143_0`1.<ExecuteInternal>b__0(Context ctx, CancellationToken ct)
   at Polly.RetrySyntax.<>c__DisplayClass12_1.<WaitAndRetry>b__1(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass12_0.<WaitAndRetry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.ExecuteInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Xrm.RemotePlugin.Client.SandboxFabricPlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Xrm.RemotePlugin.Client.ResilientSandboxPlugin.<>c__DisplayClass11_1.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.Client.ResilientSandboxPlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.RemotePluginExecute(IServiceProvider serviceProvider, ILifetimeScope lifetimeScope)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --

**Comment by JTMartin64** [comment]
Hello, I'm following up on my post above regarding the issues I'm having w/ the msdyncrmWorkflowTools.CloneRecord workflow activity being used to copy Quote Products.  Based on some of the posts above, it looks as if it can do this.  Am I missing something in my setup?  here is the link to my original post: https://github.com/demianrasko/Dynamics-365-Workflow-Tools/issues/208#issuecomment-800409432  Thank You.
