### ISSUE TITLE
Cannot import the solution to Power automate with no d365 apps

### ISSUE THREAD

**Issue by MateRadz** [demianrasko/Dynamics-365-Workflow-Tools#248]
Hi,

maybe this is not a bug but feature, but I tried to import this solution on "naked" CDS environment. It seems it lacks at least "Marketing List".

Is it at all possible to do so?

If so what is the minimum set of entities this solution expects to see in the target environment?

Is it possible, if those entities would be created by some solution?

Microsoft.Crm.Tools.ImportExportPublish.ImportPluginTypesException: Plugin Types import: FAILURE. Error: Plugin: msdyncrmWorkflowTools, Version=1.0.61.1, Culture=neutral, PublicKeyToken=416e876b9bee261e of PluginTypeName: Microsoft.Crm.Entities.PluginType caused an exception.: Invalid CrmReferenceTarget: The entity list doesn't exist. Property: Marketing List ---&gt; Microsoft.Crm.CrmException: Invalid CrmReferenceTarget: The entity list doesn't exist. Property: Marketing List
   at Microsoft.Crm.ObjectModel.WorkflowActivityValidator.ValidateNet4SpecialTypeAttribute(Type propertyType, String propertyName, String[] activityParameterTargets, String[] attributeTargets, String attributeName, DynamicMetadataCache metadata)
   at Microsoft.Crm.ObjectModel.WorkflowSandboxCustomActivityValidator.ValidateNet4SpecialTypeAttribute(CustomActivityParameterInfo customActivityParameterInfo, DynamicMetadataCache metadata)
   at Microsoft.Crm.ObjectModel.WorkflowSandboxCustomActivityValidator.ValidateInternal()
   at Microsoft.Crm.ObjectModel.PluginValidatorBase.Validate()
   at Microsoft.Crm.ObjectModel.PluginTypeValidator.ValidateInternal()
   at Microsoft.Crm.ObjectModel.PluginValidatorBase.Validate()
   at Microsoft.Crm.ObjectModel.PluginTypeServiceInternal`1.Create(IBusinessEntity entity, ExecutionContext context)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportPluginAssemblyHandler.ImportItem()
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Tools.ImportExportPublish.ImportPluginAssemblyHandler.ImportItem()

The reason why we do not need to use e.g. d365 for Sales is the fact that we are using only custom entities in our solution hence, we could save some money on licensing.

**Comment by MateRadz** [comment]
I managed to do this by altering the customisations.xml file and leaving only the relevant plug ins for me:

<PluginTypes>
      <PluginType AssemblyQualifiedName="msdyncrmWorkflowTools.GetRecordID, msdyncrmWorkflowTools, Version=1.0.61.1, Culture=neutral, PublicKeyToken=416e876b9bee261e" PluginTypeId="605363a7-9e02-4879-870b-b485ef49d998" Name="msdyncrmWorkflowTools.GetRecordID">
          <FriendlyName>04d6f4fb-7a73-499d-948f-ca5eb888b154</FriendlyName>
          <WorkflowActivityGroupName>msdyncrmWorkflowTools (1.0.61.1)</WorkflowActivityGroupName>
        </PluginType>
        <PluginType AssemblyQualifiedName="msdyncrmWorkflowTools.StringFunctions, msdyncrmWorkflowTools, Version=1.0.61.1, Culture=neutral, PublicKeyToken=416e876b9bee261e" PluginTypeId="f70e92a9-eef0-441f-bd8f-966fba351dff" Name="msdyncrmWorkflowTools.StringFunctions">
          <FriendlyName>22ca480e-27c4-489f-9e6b-eced808b3e99</FriendlyName>
          <WorkflowActivityGroupName>msdyncrmWorkflowTools (1.0.61.1)</WorkflowActivityGroupName>
        </PluginType>
        <PluginType AssemblyQualifiedName="msdyncrmWorkflowTools.UpdateChildRecords, msdyncrmWorkflowTools, Version=1.0.61.1, Culture=neutral, PublicKeyToken=416e876b9bee261e" PluginTypeId="37e30e5c-0393-4328-b895-cffb74d8de77" Name="msdyncrmWorkflowTools.UpdateChildRecords">
          <FriendlyName>0895844a-f0f2-4925-b582-e94e533dcac3</FriendlyName>
          <WorkflowActivityGroupName>msdyncrmWorkflowTools (1.0.61.1)</WorkflowActivityGroupName>
        </PluginType>
        <PluginType AssemblyQualifiedName="msdyncrmWorkflowTools.UpdateChildRecords, msdyncrmWorkflowTools, Version=1.0.61.1, Culture=neutral, PublicKeyToken=416e876b9bee261e" PluginTypeId="37e30e5c-0393-4328-b895-cffb74d8de77" Name="msdyncrmWorkflowTools.UpdateChildRecords">
          <FriendlyName>0895844a-f0f2-4925-b582-e94e533dcac3</FriendlyName>
          <WorkflowActivityGroupName>msdyncrmWorkflowTools (1.0.61.1)</WorkflowActivityGroupName>
        </PluginType>
      </PluginTypes>

These plug ins do not require specific d365 entities - and solution installs clean on pure Dataverse environment.
