### ISSUE TITLE
Problem setting BPF stage

### ISSUE THREAD

**Issue by jrichview** [demianrasko/Dynamics-365-Workflow-Tools#266]
We created a very very simple workflow that triggers when a case record is assigned to the user, and its job is to set the BPF stage for the case to a stage called "Case Picked & In Progress". 

The flow fails on the attempt to set the BPF stage with the error message "Process stage Case Picked & In Progress not found."

Here is an image snippet from the process showing the process name:
![image](https://user-images.githubusercontent.com/2236908/176750007-d1c5da5f-d71e-4308-96fc-577cc934a51e.png)

The simple workflow:
![image](https://user-images.githubusercontent.com/2236908/176750314-76a78133-b7cc-42e2-afc9-c0bfefa313f1.png)

The input parameters:
![image](https://user-images.githubusercontent.com/2236908/176750521-5b3004bc-d74c-4094-887d-b7858c678481.png)

As you can see, the stage name is just hard-coded text.

_*** PLEASE NOTE: I was thinking the problem could be the ampersand so I encoded the text as "&amp;" and tried again but got the same error message._

I'm not really sure how to tell you to reproduce this other than to create a BPF and name one of the stages with the same name and create a workflow that tries to set the stage to that particular one when the case is picked from the queue (i.e. the "Worked By" field gets set).

**Expected behavior**
BPF stage should be set to the requested stage.

This is Dynamics 365 (cloud, not on-prem).

Version of the tools is 1.0.60.1

**Comment by jrichview** [comment]
UPDATE: I discovered that there was an extra space between the ampersand and the next word. I updated the flow and re-tested and now every time it fails with the following:

![image](https://user-images.githubusercontent.com/2236908/176783621-4d6b2b21-a54b-4ea4-b6cb-7927c6cfa818.png)

Details:

Workflow suspended temporarily due to error: Exception type: Microsoft.Crm.CrmException
Message: The plug-in execution failed because the Sandbox Worker process crashed. This is typically due to an error in the plug-in code. Please refer to this document: https://go.microsoft.com/fwlink/?linkid=2189390
Microsoft.Xrm.RemotePlugin.Grpc.ExceptionHandlers.SandboxFabricWorkerCommunicationException: Error communicating with SandboxFabric Worker ---> Grpc.Core.RpcException: Status(StatusCode="DeadlineExceeded", Detail="Deadline Exceeded", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1656624640.756000000","description":"Error received from peer ipv4:52.250.229.136:443","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1068,"grpc_message":"Deadline Exceeded","grpc_status":4}")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +0xc
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +0x28
   at Grpc.Core.Internal.ClientResponseStream`2.<MoveNext>d__5.MoveNext() +0x11b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +0xc
   at Microsoft.Xrm.RemotePlugin.Grpc.SandboxFabricGrpcClient.<HandleGrpcStreams>d__50.MoveNext() +0x53c
   --- End of inner exception stack trace ---
   at Microsoft.Xrm.RemotePlugin.Grpc.SandboxFabricGrpcClient.<>c__DisplayClass50_2.<HandleGrpcStreams>b__1() +0xa5
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties) +0x90
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action) +0x13
   at Microsoft.Xrm.RemotePlugin.Grpc.SandboxFabricGrpcClient.<HandleGrpcStreams>d__50.MoveNext() +0x603
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +0xc
   at Microsoft.Xrm.RemotePlugin.Grpc.SandboxFabricGrpcClient.<HandleGrpcStreams>d__50.MoveNext() +0x801
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +0xc
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +0x28
   at Microsoft.Xrm.RemotePlugin.Grpc.SandboxFabricGrpcClient.<>c__DisplayClass48_0.<<ExecuteInternalAsync>b__0>d.MoveNext() +0x33b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +0xc
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +0x28
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.<ExecuteRootAsync>d__15`1.MoveNext() +0x167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +0xc
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +0x28
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.<ExecuteRootAsync>d__20`1.MoveNext() +0x0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +0xc
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +0x28
   at Microsoft.Xrm.RemotePlugin.Grpc.SandboxFabricGrpcClient.<>c__DisplayClass46_0.<ExecutePluginInternal>b__1() +0x36
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties) +0x91
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func) +0x0
   at Microsoft.Xrm.RemotePlugin.Grpc.SandboxFabricGrpcClient.ExecutePluginInternal(IRemotePluginRequest pluginRequest, ExecuteRequest executeRequest, Guid executionId, ISandboxFabricDuplexCommunicationHandler communicationHandler, Boolean returnTraceInfo, Guid organizationId, SandboxFabricCallTracker sandboxFabricCallTracker) +0x3d3: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #4F606F26
   at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricClientTelemetryInterceptor.<>c__DisplayClass3_0.<Intercept>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricClientTelemetryInterceptor.Intercept(IInvocation invocation, IExecutionContext context, SandboxFabricCallTracker sandboxFabricCallTracker)
   at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricCodeUnitExecuteBaseInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ISandboxFabricCodeUnitProxy.Execute(ILifetimeScope scope, IExecutionContext context, SandboxFabricCallTracker& sandboxFabricCallTracker)
   at Microsoft.Xrm.RemotePlugin.Client.SandboxFabricPlugin.<>c__DisplayClass4_1.<Execute>b__3()
   at Polly.Policy.<>c__DisplayClass150_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass143_0`1.<ExecuteInternal>b__0(Context ctx, CancellationToken ct)
   at Polly.RetrySyntax.<>c__DisplayClass12_1.<WaitAndRetry>b__1(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass12_0.<WaitAndRetry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.ExecuteInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Xrm.RemotePlugin.Client.SandboxFabricPlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Xrm.RemotePlugin.Client.ResilientSandboxPlugin.<>c__DisplayClass13_1.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.Client.ResilientSandboxPlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.RemotePluginExecute(IServiceProvider serviceProvider, ILifetimeScope lifetimeScope, IExecutionContext executionContext, ILogger logger)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --
