### ISSUE TITLE
Sandbox goes into faulted state on QueryValue function

### ISSUE THREAD

**Issue by allessonne** [demianrasko/Dynamics-365-Workflow-Tools#47]
I am using the query value function to query values from a none related custom entity in a workflow which I am using later in the workflow. The function itself works fine. The workflow executes as child workflow on create or update of a customer record. The custom records are updated/created in the morning and 2000-3000 or more records can be affected.
The sandbox service stops and all remaining system jobs fail and I need to run all records manualy.
Do you know a workaround or do I simply need to rewrite my workflow by removing the Query Value function and finding a different way to handle the operation?

CRM2016 on premise, msdyncrmWorkflowTools (1.0.40.0)

The workflow fails for 1000-2000 records every morning with the error message:
Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.QueryValues: System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.QueryValues]
[msdyncrmWorkflowTools (1.0.40.0): Query Values]

Load CRM Service from context --- OK
EntityName: ap_translation - Attribute1:ap_translation - Attribute2:ap_translationtype - FilterAttribute1:nov_ownerlanguage - FilterAttribute2:nov_sourcetext - ValueAttribute1:CROATIA ValueAttribute2:New
Executing Query...
error: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state. - 
Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrImmutable()
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.ServiceModel.ICommunicationObject.Open()
   at Microsoft.Crm.Sandbox.SandboxClientBase`1.Open()
   at Microsoft.Crm.Sandbox.SandboxClientBase`1.get_Proxy()
   at Microsoft.Crm.Sandbox.SandboxOrganizationService.ProcessException(Exception e, SandboxSdkClient client)
   at Microsoft.Crm.Sandbox.SandboxOrganizationService.Execute(String operation, Byte[] serializedRequest)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [1]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Crm.Sandbox.ISandboxOrganizationService.Execute(String operation, Byte[] serializedRequest)
   at Microsoft.Crm.Sandbox.SandboxOrganizationServiceWrapper.ExecuteInternal(OrganizationRequest request)
   at Microsoft.Crm.Sandbox.SandboxOrganizationServiceWrapper.RetrieveMultipleInternal(QueryBase query)
   at msdyncrmWorkflowTools.QueryValues.Execute(CodeActivityContext executionContext)

Error Message:

Unhandled Exception: Microsoft.Crm.CrmException: Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.QueryValues: System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.Execute(IExecutionContext context)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)

**Comment by demianrasko** [comment]
Hi allessonne, 
Please check this points:
- are you executing a real time workflow?
- are you using bulk operation for the 2/3K record creation/update?

I think that maybe you have some locking issues in the databse...
