### ISSUE TITLE
Clone Record : Object reference not set to an instance of an object. Error

### ISSUE THREAD

**Issue by rob-ritchie** [demianrasko/Dynamics-365-Workflow-Tools#86]
### Expected behavior and actual behavior.
Receiving an unhandled exception error:

Plugin Trace:

[msdyncrmWorkflowTools: msdyncrmWorkflowTools.CloneRecord]
[msdyncrmWorkflowTools (1.0.52.0): Clone Record]

Load CRM Service from context --- OK
ObjectTypeCode=10213--ParentId=4d2b32b5-4763-e811-a951-000d3a3acbf2

Error Message:

Unhandled Exception: Microsoft.Crm.CrmException: Unexpected exception from plug-in (Execute): msdyncrmWorkflowTools.CloneRecord: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.ProcessException(Exception originalException, IExecutionContext context, SandboxClient client, SandboxCallTracker callTracker, Boolean isSafeToRetry, DateTime performanceExecutionStartTime, SandboxTracker tracker, Guid parentExecutionId, CrmException& crmException, String& assemblyContents)
   at Microsoft.Crm.Sandbox.SandboxCodeUnit.Execute(IExecutionContext context)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)

### Steps to reproduce the problem (screenshots are really usefull)
Clone Record Workflow

### CRM Version - online/onpremise - WorkflowTools version
Online: 9.0

**Comment by MfreemanRING** [comment]
This is happening to me too.  I was originally looking for a way to clone the child records in addition to parent.  I had the cloning part working fine with a slightly earlier release of this tool (1.0.38.0).  I saw the newer release (1.0.50.1) now included cloning the children and was supported on our version of CRM.  So I updated the solution and tested.  Cloning still worked.  Now I moved on to adding the Cloning Child option, couldn't get it to work, figured I was getting the param's all wrong.  So I removed that step for now.  Then I go back to my Parent Cloning step... still working.  Saw it updated too.  Noticed it had an option to include a "Prefix".  Thought I'd try it.  The workflow hasn't worked since.  Even went back and removed the prefix, but it is still failing with this same error.  Now I'm just stuck.  Any solution would be greatly appreciated.  Our company is using OnPrem 8.1.0.359

**Comment by fvakiliev** [comment]
I get this error too. Clone salesorder.
On-premises 8.2.2.112
```
Sync workflow failed with error message - Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Activities.WorkflowApplication.Invoke(Activity activity, IDictionary`2 inputs, WorkflowInstanceExtensionManager extensions, TimeSpan timeout)
   at System.Activities.WorkflowInvoker.Invoke(Activity workflow, IDictionary`2 inputs, TimeSpan timeout, WorkflowInstanceExtensionManager extensions)
   at Microsoft.Crm.Workflow.SynchronousRuntime.SynchronousWorkflowActivityHost.ExecuteWorkflowUsingInvoker(Activity workflow, ICommonWorkflowContext context)
   at Microsoft.Crm.Workflow.SynchronousRuntime.SynchronousWorkflowActivityHost.StartWorkflow(WorkflowActivationData activationData, ICommonWorkflowContext context)
, error code - -2147220970
```

**Comment by MfreemanRING** [comment]
Well... cloning the parent started working again.  Not sure why.  I deleted the workflow and recreated it 2 times.  I did change the workflow to a real-time workflow when it finally worked.  Then I created a standard workflow and it worked too, so I'm baffled and an little apprehensive on using something that is this squirrely.  Will test it thoroughly before releasing to production.

**Comment by demianrasko** [comment]
thanks MfreemanRING, I always recomend to do so.
This tool is a communty tool, and I'm not the only one developing it, and also we don't have a group of testers behind us to test every case.
I really appreciate your feedback and contributions to make it better.

thanks!
